### ISSUE TITLE
Close *scratch* window on startup

### ISSUE THREAD

**Issue by yazdani** [code-iai/ros_emacs_utils#13]

**Comment by fairlight1337** [comment]
Is that an issue someone is working on? Or do you have a proposition you're about to commit and use this issue as a reminder, @yazdani?

**Comment by gaya-** [comment]
This was a reminder for me. Should be solved by https://github.com/code-iai/ros_emacs_utils/commit/2e90597094b6f192e9ba7424ab19b71f2dbd0042. Unfortunately, the last Indigo sync was just two days ago, so hell knows when the next one will be. So you could either update your roslisp_repl using the ros-shadow-fixed Debian repo (in ``/etc/apt/sources.list.d/ros-lates.list`` instead of ``ros/ubuntu`` use ``ros-shadow-fixed/ubuntu``) or manually add the one line with ``(delete-other-windows)`` into your ``repl-config.el`` under ``sudo``. Neither of the two is recommended though :). Alternatively, you could wait another 3-4 weeks until the next sync...
